// src/pages/LanguageSelectionPage.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
    <div class="max-w-md w-full">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">{{ t.aiTrainer }}</h1>
        <p class="text-gray-600">{{ t.welcomeToOnboarding }}</p>
      </div>

      <div class="card">
        <h2 class="text-xl font-semibold text-gray-900 mb-6">{{ t.selectLanguageTitle }}</h2>
        <p class="text-sm text-gray-600 mb-6">
                      {{ t.selectLanguageDescription }}<br>
            {{ t.selectLanguageDescriptionRu }}
        </p>
        
        <div class="space-y-4">
          <!-- English Option -->
          <button
            @click="selectLanguage('en')"
            class="w-full p-4 border-2 border-gray-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all duration-200 text-left"
            :class="selectedLanguage === 'en' ? 'border-primary-500 bg-primary-50' : ''"
          >
            <div class="flex items-center">
              <div class="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center mr-3">
                <span class="text-sm font-bold text-blue-600">EN</span>
              </div>
              <div>
                <div class="font-medium text-gray-900">English</div>
                <div class="text-sm text-gray-500">{{ t.continueInEnglish }}</div>
              </div>
            </div>
          </button>

          <!-- Russian Option -->
          <button
            @click="selectLanguage('ru')"
            class="w-full p-4 border-2 border-gray-200 rounded-lg hover:border-primary-500 hover:bg-primary-50 transition-all duration-200 text-left"
            :class="selectedLanguage === 'ru' ? 'border-primary-500 bg-primary-50' : ''"
          >
            <div class="flex items-center">
              <div class="w-8 h-8 bg-red-100 rounded-full flex items-center justify-center mr-3">
                <span class="text-sm font-bold text-red-600">RU</span>
              </div>
              <div>
                <div class="font-medium text-gray-900">Русский</div>
                <div class="text-sm text-gray-500">{{ t.continueInRussian }}</div>
              </div>
            </div>
          </button>
        </div>

        <div class="mt-6">
          <button
            @click="continueToOnboarding"
            :disabled="!selectedLanguage"
            class="w-full btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {{ selectedLanguage === 'ru' ? t.continueInRussian : t.continueInEnglish }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18nStore } from '@/stores/i18n.store'
import type { Language } from '@/stores/i18n.store'

const router = useRouter()
const i18nStore = useI18nStore()

const { t } = i18nStore

const selectedLanguage = ref<Language | null>(null)

function selectLanguage(lang: Language) {
  selectedLanguage.value = lang
  i18nStore.setLanguage(lang)
}

function continueToOnboarding() {
  if (!selectedLanguage.value) return
  
  // Store language preference
  localStorage.setItem('selectedLanguage', selectedLanguage.value)
  
  // Set language in i18n store
  i18nStore.setLanguage(selectedLanguage.value)
  
  // Navigate to onboarding selection
  router.push('/onboarding')
}
</script>

// src/pages/LanguageSelectionPage.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useI18nStore } from '../stores/i18n.store'
import { useProfileStore } from '../stores/profile.store'
import { useTranslations } from '../stores/i18n.store'

const LanguageSelectionPage: React.FC = () => {
  const navigate = useNavigate()
  const { setLanguage } = useI18nStore()
  const { createProfile } = useProfileStore()
  const t = useTranslations()
  const [selectedLanguage, setSelectedLanguage] = useState<'en' | 'ru' | null>(null)

  const handleLanguageSelect = (language: 'en' | 'ru') => {
    setSelectedLanguage(language)
  }

  const handleContinue = async () => {
    if (!selectedLanguage) return

    try {
      // Set language in i18n store
      setLanguage(selectedLanguage)
      
      // Mark that app has been launched before and navigate first
      localStorage.setItem('ai-trainer:has-launched', 'true')

      // Navigate to entry step first
      navigate('/entry')

      // Then create basic profile with selected language
      await createProfile({
        name: '', // Will be updated in later steps
        gender: 'male', // Will be updated in later steps
        age: 0, // Will be updated in later steps
        height: 0, // Will be updated in later steps
        weight: 0, // Will be updated in later steps
        goal: '', // Will be updated in later steps
        constraints: [],
        equipment: [],
        frequency: 3,
        duration: 30,
        language: selectedLanguage,
        goalsDetailed: ''
      })

    } catch (error) {
      console.error('Failed to create profile:', error)
      alert(t.error || 'Failed to create profile')
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            {t.aiTrainer}
          </h1>
          <p className="text-gray-600 mb-8">
            {t.selectLanguageDescription}
          </p>
          
          <div className="space-y-4 mb-8">
            <button
              onClick={() => handleLanguageSelect('en')}
              className={`w-full py-3 px-4 border rounded-lg hover:bg-gray-50 transition-colors text-left ${
                selectedLanguage === 'en' 
                  ? 'border-blue-500 bg-blue-50' 
                  : 'border-gray-300'
              }`}
            >
              <div className="flex items-center space-x-3">
                <span className="text-2xl">🇺🇸</span>
                <div>
                  <div className="font-medium text-gray-900">{t.english}</div>
                  <div className="text-sm text-gray-500">English</div>
                </div>
              </div>
            </button>
            
            <button
              onClick={() => handleLanguageSelect('ru')}
              className={`w-full py-3 px-4 border rounded-lg hover:bg-gray-50 transition-colors text-left ${
                selectedLanguage === 'ru' 
                  ? 'border-blue-500 bg-blue-50' 
                  : 'border-gray-300'
              }`}
            >
              <div className="flex items-center space-x-3">
                <span className="text-2xl">🇷🇺</span>
                <div>
                  <div className="font-medium text-gray-900">{t.russian}</div>
                  <div className="text-sm text-gray-500">Русский</div>
                </div>
              </div>
            </button>
          </div>

          {/* Continue Button */}
          <button
            onClick={handleContinue}
            disabled={!selectedLanguage}
            className={`w-full py-3 px-4 rounded-lg font-medium transition-colors ${
              selectedLanguage
                ? 'bg-blue-600 text-white hover:bg-blue-700'
                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
            }`}
          >
            {t.continue}
          </button>
        </div>
      </div>
    </div>
  )
}

export default LanguageSelectionPage
