// src/pages/NotFound.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center">
    <div class="text-center">
      <div class="text-6xl font-bold text-gray-300 mb-4">404</div>
      <h1 class="text-2xl font-semibold text-gray-900 mb-4">Page Not Found</h1>
      <p class="text-gray-600 mb-8">
        The page you're looking for doesn't exist.
      </p>
      <router-link 
        to="/" 
        class="btn-primary"
      >
        Go Home
      </router-link>
    </div>
  </div>
</template>

// src/pages/NotFound.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import { useTranslations } from '../stores/i18n.store'

const NotFound: React.FC = () => {
  const t = useTranslations()

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="max-w-md w-full text-center">
        <div className="text-6xl font-bold text-gray-300 mb-4">404</div>
        <h1 className="text-2xl font-bold text-gray-900 mb-4">
          Page Not Found
        </h1>
        <p className="text-gray-600 mb-8">
          The page you're looking for doesn't exist.
        </p>
        <Link
          to="/"
          className="btn-primary"
        >
          {t.home}
        </Link>
      </div>
    </div>
  )
}

export default NotFound
