// src/features/onboarding/OnboardingGoals.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
    <div class="max-w-md w-full">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">Welcome to AI Trainer</h1>
        <p class="text-gray-600">Let's set up your fitness journey</p>
      </div>

      <div class="card">
        <h2 class="text-xl font-semibold text-gray-900 mb-6">What's your main goal?</h2>
        
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Goal Type -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-3">Fitness Goal</label>
            <div class="space-y-3">
              <label 
                v-for="goal in goals" 
                :key="goal.type"
                class="flex items-center p-4 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors"
                :class="selectedGoal === goal.type ? 'border-primary-500 bg-primary-50' : 'border-gray-200'"
              >
                <input
                  type="radio"
                  :value="goal.type"
                  v-model="selectedGoal"
                  class="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300"
                />
                <div class="ml-3">
                  <div class="text-sm font-medium text-gray-900">{{ goal.title }}</div>
                  <div class="text-sm text-gray-500">{{ goal.description }}</div>
                </div>
              </label>
            </div>
          </div>

          <!-- Goal Description -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Describe your goal in detail
            </label>
            <textarea
              v-model="goalDescription"
              rows="3"
              class="input-field"
              placeholder="e.g., I want to lose 10kg in 6 months to feel more confident..."
              required
            ></textarea>
          </div>

          <!-- Target Weight (optional) -->
          <div v-if="selectedGoal === 'weight_loss' || selectedGoal === 'muscle_gain'">
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Target Weight (kg) - Optional
            </label>
            <input
              v-model.number="targetWeight"
              type="number"
              min="30"
              max="250"
              class="input-field"
              placeholder="e.g., 70"
            />
          </div>

          <!-- Target Event (optional) -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              Target Event or Date - Optional
            </label>
            <input
              v-model="targetEvent"
              type="text"
              class="input-field"
              placeholder="e.g., Summer vacation, Wedding, Marathon..."
            />
          </div>

          <!-- Navigation -->
          <div class="flex justify-end">
            <button
              type="submit"
              :disabled="!selectedGoal || !goalDescription"
              class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const selectedGoal = ref('')
const goalDescription = ref('')
const targetWeight = ref<number | undefined>()
const targetEvent = ref('')

const goals = [
  {
    type: 'weight_loss',
    title: 'Weight Loss',
    description: 'Lose body fat and get leaner'
  },
  {
    type: 'muscle_gain',
    title: 'Muscle Gain',
    description: 'Build strength and muscle mass'
  },
  {
    type: 'endurance',
    title: 'Endurance',
    description: 'Improve cardiovascular fitness'
  },
  {
    type: 'strength',
    title: 'Strength',
    description: 'Increase overall strength'
  },
  {
    type: 'general_fitness',
    title: 'General Fitness',
    description: 'Stay healthy and active'
  }
]

function handleSubmit() {
  if (!selectedGoal.value || !goalDescription.value) return

  // Store goal data in localStorage for the onboarding flow
  const goalData = {
    type: selectedGoal.value,
    description: goalDescription.value,
    targetWeight: targetWeight.value,
    targetEvent: targetEvent.value
  }
  
  localStorage.setItem('onboarding-goal', JSON.stringify(goalData))
  
  // Navigate to next step
  router.push('/onboarding/constraints')
}
</script>

// src/features/onboarding/OnboardingGoals.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useProfileStore } from '../../stores/profile.store'
import { useTranslations } from '../../stores/i18n.store'
import type { Goal } from '../../types/models'

const OnboardingGoals: React.FC = () => {
  const navigate = useNavigate()
  const { saveProfile } = useProfileStore()
  const t = useTranslations()
  
  const [goals, setGoals] = useState<('weight_loss' | 'muscle_gain' | 'endurance' | 'strength' | 'general_fitness')[]>([])
  const [targetWeight, setTargetWeight] = useState('')
  const [targetEvent, setTargetEvent] = useState('')
  const [description, setDescription] = useState('')

  const goalOptions: Array<{ value: 'weight_loss' | 'muscle_gain' | 'endurance' | 'strength' | 'general_fitness'; label: string }> = [
    { value: 'weight_loss', label: 'Weight Loss' },
    { value: 'muscle_gain', label: 'Muscle Gain' },
    { value: 'endurance', label: 'Endurance' },
    { value: 'strength', label: 'Strength' },
    { value: 'general_fitness', label: 'General Fitness' }
  ]

  const handleGoalToggle = (goalValue: 'weight_loss' | 'muscle_gain' | 'endurance' | 'strength' | 'general_fitness') => {
    setGoals(prev => 
      prev.includes(goalValue) 
        ? prev.filter(g => g !== goalValue)
        : [...prev, goalValue]
    )
  }

  const handleNext = async () => {
    if (goals.length === 0) {
      alert('Please select at least one goal')
      return
    }

    try {
      const goal: Goal = {
        types: goals,
        targetWeight: targetWeight ? parseFloat(targetWeight) : undefined,
        targetEvent: targetEvent || undefined,
        description: description || ''
      }

      // Update existing profile with goals
      await saveProfile({
        goal,
        goalsDetailed: description || ''
      })

      navigate('/onboarding/constraints')
    } catch (error) {
      console.error('Failed to save goals:', error)
      alert('Failed to save goals')
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            What are your fitness goals?
          </h1>
          <p className="text-gray-600">
            Select all that apply
          </p>
        </div>

        <div className="space-y-6">
          {/* Goal Selection */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Primary Goals
            </label>
            <div className="space-y-2">
              {goalOptions.map(option => (
                <label key={option.value} className="flex items-center">
                  <input
                    type="checkbox"
                    checked={goals.includes(option.value)}
                    onChange={() => handleGoalToggle(option.value)}
                    className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                  />
                  <span className="ml-3 text-gray-700">{option.label}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Target Weight */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Target Weight (kg) - Optional
            </label>
            <input
              type="number"
              value={targetWeight}
              onChange={(e) => setTargetWeight(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              placeholder="e.g., 70"
            />
          </div>

          {/* Target Event */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Target Event - Optional
            </label>
            <input
              type="text"
              value={targetEvent}
              onChange={(e) => setTargetEvent(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              placeholder="e.g., Marathon in 6 months"
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Additional Description - Optional
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              placeholder="Describe your fitness journey..."
            />
          </div>

          {/* Navigation */}
          <div className="flex justify-end space-x-4 pt-4">
            <button
              onClick={handleNext}
              disabled={goals.length === 0}
              className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {t.next}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default OnboardingGoals
