// src/ui/organisms/onboarding/OnboardingMetrics.tsx
import React, { useState, useEffect } from 'react'
import { useOnboardingStore } from '@stores/onboarding.store'
import { useTranslations } from '@stores/i18n.store'
import OnboardingLayout from '@templates/OnboardingLayout'

const OnboardingMetrics: React.FC = () => {
  const { draft, updateDraft } = useOnboardingStore()
  const t = useTranslations()
  
  const [gender, setGender] = useState<'male' | 'female' | 'other'>(draft.gender || 'male')
  const [age, setAge] = useState(draft.age?.toString() || '')
  const [height, setHeight] = useState(draft.height?.toString() || '')
  const [weight, setWeight] = useState(draft.weight?.toString() || '')

  const genderLabels = {
    male: t.onboarding?.metrics?.male || 'Male',
    female: t.onboarding?.metrics?.female || 'Female',
    other: t.onboarding?.metrics?.other || 'Other'
  }

  useEffect(() => {
    // Update draft when local state changes
    updateDraft({
      gender,
      age: age ? parseInt(age) : undefined,
      height: height ? parseInt(height) : undefined,
      weight: weight ? parseFloat(weight) : undefined
    })
  }, [gender, age, height, weight, updateDraft])

  const canProceed = age && height && weight

  return (
    <OnboardingLayout
      stepNumber={3}
      stepTitle={t.onboarding?.metrics?.title || 'Basic Information'}
      stepDescription={t.onboarding?.metrics?.description || 'Help us personalize your experience'}
      canProceed={!!canProceed}
    >
      <div className="space-y-6">
        {/* Gender Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-3">
            {t.onboarding?.metrics?.gender || 'Gender'}
          </label>
          <div className="space-y-3">
            {(['male', 'female', 'other'] as const).map(option => (
              <label key={option} className="flex items-center">
                <input
                  type="radio"
                  name="gender"
                  value={option}
                  checked={gender === option}
                  onChange={(e) => setGender(e.target.value as 'male' | 'female' | 'other')}
                  className="border-gray-300 text-primary-600 focus:ring-primary-500"
                />
                <span className="ml-3 text-gray-700">{genderLabels[option]}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Age */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            {t.onboarding?.metrics?.age || 'Age (years)'}
          </label>
          <input
            type="number"
            value={age}
            onChange={(e) => setAge(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
            placeholder={t.onboarding?.metrics?.agePlaceholder || 'e.g., 25'}
            min="13"
            max="100"
          />
        </div>

        {/* Height */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            {t.onboarding?.metrics?.height || 'Height (cm)'}
          </label>
          <input
            type="number"
            value={height}
            onChange={(e) => setHeight(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
            placeholder={t.onboarding?.metrics?.heightPlaceholder || 'e.g., 175'}
            min="100"
            max="250"
          />
        </div>

        {/* Weight */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            {t.onboarding?.metrics?.weight || 'Weight (kg)'}
          </label>
          <input
            type="number"
            value={weight}
            onChange={(e) => setWeight(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
            placeholder={t.onboarding?.metrics?.weightPlaceholder || 'e.g., 70'}
            min="30"
            max="300"
            step="0.1"
          />
        </div>
      </div>
    </OnboardingLayout>
  )
}

export default OnboardingMetrics

// src/features/onboarding/OnboardingMetrics.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
    <div class="max-w-md w-full">
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">{{ t.aiTrainer }}</h1>
        <p class="text-gray-600">{{ t.step }} 5 {{ t.of }} 6</p>
      </div>

      <div class="card">
        <h2 class="text-xl font-semibold text-gray-900 mb-6">{{ t.tellUsAboutYourself }}</h2>
        
        <form @submit.prevent="handleSubmit" class="space-y-6">
          <!-- Name -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ t.name }} *
            </label>
            <input
              v-model="formData.name"
              type="text"
              class="input-field"
              :placeholder="t.yourName"
              required
            />
          </div>

          <!-- Age -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ t.age }} *
            </label>
            <input
              v-model.number="formData.age"
              type="number"
              min="12"
              max="90"
              class="input-field"
              :placeholder="t.yourAge"
              required
            />
          </div>

          <!-- Gender -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ t.gender }} *
            </label>
            <select v-model="formData.gender" class="input-field" required>
              <option value="">{{ t.selectGender }}</option>
              <option value="male">{{ t.male }}</option>
              <option value="female">{{ t.female }}</option>
              <option value="other">{{ t.other }}</option>
            </select>
          </div>

          <!-- Height -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ t.height }} *
            </label>
            <input
              v-model.number="formData.height"
              type="number"
              min="100"
              max="250"
              class="input-field"
              :placeholder="t.yourHeight"
              required
            />
          </div>

          <!-- Weight -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">
              {{ t.yourWeight }} *
            </label>
            <input
              v-model.number="formData.weight"
              type="number"
              min="30"
              max="250"
              step="0.1"
              class="input-field"
              :placeholder="t.weightInKg"
              required
            />
          </div>

          <!-- Navigation -->
          <div class="flex justify-between">
            <button
              type="button"
              @click="$router.push('/onboarding/equipment')"
              class="btn-secondary"
            >
              {{ t.back }}
            </button>
            <button
              type="submit"
              :disabled="!isFormValid"
              class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ t.next }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useI18nStore } from '@/stores/i18n.store'

const router = useRouter()
const i18nStore = useI18nStore()

const { t } = i18nStore

const formData = ref({
  name: '',
  age: 25,
  gender: '',
  height: 170,
  weight: 70
})

const isFormValid = computed(() => {
  return formData.value.name.trim() && 
         formData.value.age >= 12 && 
         formData.value.age <= 90 &&
         formData.value.gender &&
         formData.value.height >= 100 && 
         formData.value.height <= 250 &&
         formData.value.weight >= 30 && 
         formData.value.weight <= 250
})

async function handleSubmit() {
  if (!isFormValid.value) return

  // Store metrics data for the next step
  localStorage.setItem('onboarding-metrics', JSON.stringify(formData.value))
  
  // Navigate to next step
  router.push('/onboarding/frequency')
}
</script>
