// src/components/WorkoutForm.vue
<template>
  <form @submit.prevent="handleSubmit" class="space-y-6">
    <!-- Mode Toggle -->
    <div class="bg-gray-50 p-4 rounded-lg">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg font-medium text-gray-900">{{ t.workoutMode }}</h3>
        <div class="flex space-x-2">
          <button
            type="button"
            @click="setMode('form')"
            :class="[
              'px-4 py-2 rounded-lg font-medium transition-colors',
              mode === 'form' 
                ? 'bg-primary-600 text-white' 
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            ]"
          >
            {{ t.formMode }}
          </button>
          <button
            type="button"
            @click="setMode('text')"
            :class="[
              'px-4 py-2 rounded-lg font-medium transition-colors',
              mode === 'text' 
                ? 'bg-primary-600 text-white' 
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            ]"
          >
            {{ t.textMode }}
          </button>
        </div>
      </div>
      
      <!-- Text Mode Description -->
      <div v-if="mode === 'text'" class="text-sm text-gray-600">
        <p class="mb-2">{{ t.textModeDescription }}</p>
        <div class="bg-white p-3 rounded border text-xs font-mono">
          {{ t.textModeExample }}
        </div>
      </div>
    </div>

    <!-- Text Mode Input -->
    <div v-if="mode === 'text'" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          {{ t.workoutDescription }}
        </label>
        <textarea
          v-model="workoutText"
          rows="8"
          class="input-field"
          :placeholder="t.workoutDescriptionPlaceholder"
          required
        ></textarea>
        <p class="text-xs text-gray-500 mt-1">
          {{ t.workoutDescriptionHelp }}
        </p>
      </div>
      
      <div class="flex justify-end">
        <button
          type="button"
          @click="parseWorkoutText"
          :disabled="!workoutText.trim() || isParsing"
          class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span v-if="isParsing">{{ t.parsing }}</span>
          <span v-else>{{ t.parseWorkout }}</span>
        </button>
      </div>
    </div>

    <!-- Combined Workout Header -->
    <div v-if="mode === 'form'" class="bg-blue-50 p-4 rounded-lg">
      <h3 class="text-lg font-medium text-blue-900 mb-2">{{ t.combinedWorkout }}</h3>
      <p class="text-sm text-blue-700">
        {{ t.combinedWorkoutDescription || 'Add multiple exercises to create a comprehensive workout session.' }}
      </p>
    </div>

    <!-- Exercises List -->
    <div v-if="mode === 'form'" class="space-y-4">
      <div class="flex justify-between items-center">
        <h4 class="text-md font-medium text-gray-900">{{ t.exercises }}</h4>
        <button
          type="button"
          @click="addExercise"
          class="btn-secondary text-sm"
        >
          {{ t.addExercise }}
        </button>
      </div>

      <div v-for="(exercise, index) in exercises" :key="index" class="border rounded-lg p-4 bg-gray-50">
        <div class="flex justify-between items-start mb-3">
          <h5 class="font-medium text-gray-900">{{ t.exercise }} {{ index + 1 }}</h5>
          <button
            type="button"
            @click="removeExercise(index)"
            class="text-red-600 hover:text-red-700 text-sm"
            :disabled="exercises.length === 1"
          >
            {{ t.removeExercise }}
          </button>
        </div>

        <!-- Exercise Type -->
        <div class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.workoutType }}
          </label>
          <select
            v-model="exercise.type"
            class="input-field"
            required
          >
            <option value="">{{ t.selectWorkoutType }}</option>
            <option value="run">{{ t.run }}</option>
            <option value="pullups">{{ t.pullups }}</option>
            <option value="pushups">{{ t.pushups }}</option>
            <option value="plank">{{ t.plank }}</option>
            <option value="custom">{{ t.custom }}</option>
          </select>
        </div>

        <!-- Exercise Duration -->
        <div class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.durationMinutes }}
          </label>
          <input
            v-model.number="exercise.details.durationMin"
            type="number"
            min="1"
            max="480"
            class="input-field"
            required
          />
        </div>

        <!-- Dynamic Fields Based on Type -->
        <div v-if="exercise.type === 'run'" class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.distanceKm }}
          </label>
          <input
            v-model.number="exercise.details.distanceKm"
            type="number"
            step="0.1"
            min="0.1"
            max="100"
            class="input-field"
          />
          <p class="text-xs text-gray-500 mt-1">
            {{ t.distanceDescription }}
          </p>
        </div>

        <div v-if="exercise.type === 'pullups' || exercise.type === 'pushups'" class="mb-3">
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                {{ t.sets }}
              </label>
              <input
                v-model.number="exercise.details.sets"
                type="number"
                min="1"
                max="100"
                class="input-field"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">
                {{ t.reps }}
              </label>
              <input
                v-model.number="exercise.details.repsPerSet"
                type="number"
                min="1"
                max="1000"
                class="input-field"
                placeholder="Reps per set"
              />
            </div>
          </div>
        </div>

        <div v-if="exercise.type === 'plank'" class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.seconds }}
          </label>
          <input
            v-model.number="exercise.details.seconds"
            type="number"
            min="10"
            max="3600"
            class="input-field"
          />
        </div>

        <div v-if="exercise.type === 'custom'" class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.exerciseName }}
          </label>
          <input
            v-model="exercise.details.notes"
            type="text"
            class="input-field"
            :placeholder="t.exerciseNamePlaceholder"
            required
          />
        </div>

        <!-- Exercise Notes -->
        <div class="mb-3">
          <label class="block text-sm font-medium text-gray-700 mb-2">
            {{ t.notes }} ({{ t.optional }})
          </label>
          <textarea
            v-model="exercise.details.notes"
            rows="2"
            class="input-field"
            :placeholder="t.notesPlaceholder"
          ></textarea>
        </div>
      </div>
    </div>

    <!-- Date -->
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        {{ t.date }}
      </label>
      <input
        v-model="formData.date"
        type="date"
        class="input-field"
        required
      />
    </div>

    <!-- RPE -->
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        {{ t.rpe }}
      </label>
      <select v-model="formData.rpe" class="input-field">
        <option value="">{{ t.selectRPE || 'Select RPE' }}</option>
        <option v-for="i in 10" :key="i" :value="i">{{ i }} - {{ getRPEDescription(i) }}</option>
      </select>
      <p class="text-xs text-gray-500 mt-1">
        {{ t.rpeDescription }}
      </p>
    </div>

    <!-- Workout Notes -->
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-2">
        {{ t.workoutNotes || 'Workout Notes' }} ({{ t.optional }})
      </label>
      <textarea
        v-model="formData.notes"
        rows="3"
        class="input-field"
        :placeholder="t.workoutNotesPlaceholder || 'How did the workout feel overall? Any observations?'"
      ></textarea>
    </div>

    <!-- Summary -->
    <div v-if="totalCalories > 0 || totalDuration > 0" class="bg-gray-50 rounded-lg p-4">
      <div class="grid grid-cols-2 gap-4 text-sm">
        <div>
          <span class="text-gray-600">{{ t.totalCalories }}:</span>
          <span class="font-semibold text-primary-600 ml-2">{{ totalCalories }} kcal</span>
        </div>
        <div>
          <span class="text-gray-600">{{ t.totalDuration }}:</span>
          <span class="font-semibold text-primary-600 ml-2">{{ totalDuration }} {{ t.minutes || 'min' }}</span>
        </div>
      </div>
    </div>

    <!-- Submit Button -->
    <div class="flex justify-end space-x-3">
      <button
        type="button"
        @click="$emit('cancel')"
        class="btn-secondary"
      >
        {{ t.cancel }}
      </button>
      <button
        type="submit"
        :disabled="isSubmitting || !isFormValid"
        class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
      >
        <span v-if="isSubmitting">{{ t.saving }}</span>
        <span v-else>{{ editMode ? t.update : t.save }} {{ t.workout }}</span>
      </button>
    </div>
  </form>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useWorkoutsStore } from '@/stores/workouts.store'
import { useProfileStore } from '@/stores/profile.store'
import { useI18nStore } from '@/stores/i18n.store'
import { useAIStore } from '@/stores/ai.store'
import type { Workout, WorkoutExercise, WorkoutType } from '@/types/models'

interface Props {
  workout?: Workout
  editMode?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  editMode: false
})

const emit = defineEmits<{
  saved: [workout: Workout]
  cancel: []
}>()

const workoutsStore = useWorkoutsStore()
const profileStore = useProfileStore()
const i18nStore = useI18nStore()
const aiStore = useAIStore()

const { t } = i18nStore

const isSubmitting = ref(false)

// Form data
const formData = ref({
  date: new Date().toISOString().split('T')[0],
  notes: '',
  rpe: undefined as number | undefined
})

// Form state
const mode = ref<'form' | 'text'>('form')
const workoutText = ref('')
const isParsing = ref(false)

// Exercises array
const exercises = ref<WorkoutExercise[]>([
  {
    type: 'run',
    details: {
      durationMin: 30,
      distanceKm: undefined,
      sets: undefined,
      repsPerSet: undefined,
      seconds: undefined,
      notes: ''
    },
    kcalEstimated: undefined
  }
])

// Initialize form with workout data if editing
onMounted(() => {
  if (props.workout) {
    formData.value = {
      date: new Date(props.workout.date).toISOString().split('T')[0],
      notes: props.workout.exercises[0]?.details.notes || '',
      rpe: props.workout.rpe
    }
    exercises.value = [...props.workout.exercises]
  }
})

// Computed properties
const totalCalories = computed(() => {
  return exercises.value.reduce((total, exercise) => {
    return total + (exercise.kcalEstimated || 0)
  }, 0)
})

const totalDuration = computed(() => {
  return exercises.value.reduce((total, exercise) => {
    return total + (exercise.details.durationMin || 0)
  }, 0)
})

const isFormValid = computed(() => {
  if (mode.value === 'text') {
    return workoutText.value.trim().length > 0 && formData.value.date
  }
  
  return exercises.value.length > 0 && 
         exercises.value.every(exercise => 
           exercise.type && 
           exercise.details.durationMin && 
           exercise.details.durationMin > 0
         ) &&
         formData.value.date
})

// Methods
function addExercise() {
  exercises.value.push({
    type: 'run',
    details: {
      durationMin: 30,
      distanceKm: undefined,
      sets: undefined,
      repsPerSet: undefined,
      seconds: undefined,
      notes: ''
    },
    kcalEstimated: undefined
  })
}

function removeExercise(index: number) {
  if (exercises.value.length > 1) {
    exercises.value.splice(index, 1)
  }
}

function getRPEDescription(rpe: number): string {
  const descriptions: Record<number, string> = {
    1: t.rpeVeryEasy,
    2: t.rpeEasy,
    3: t.rpeLight,
    4: t.rpeModerate,
    5: t.rpeSomewhatHard,
    6: t.rpeHard,
    7: t.rpeVeryHard,
    8: t.rpeExtremelyHard,
    9: t.rpeMaximumEffort,
    10: t.rpeAbsoluteMaximum
  }
  return descriptions[rpe] || ''
}

function setMode(newMode: 'form' | 'text') {
  mode.value = newMode
  if (newMode === 'text') {
    // Clear exercises when switching to text mode
    exercises.value = []
  } else {
    // Initialize with default exercise when switching to form mode
    if (exercises.value.length === 0) {
      exercises.value = [{
        type: 'run',
        details: {
          durationMin: 30,
          distanceKm: undefined,
          sets: undefined,
          repsPerSet: undefined,
          seconds: undefined,
          notes: ''
        },
        kcalEstimated: undefined
      }]
    }
  }
}

async function parseWorkoutText() {
  if (!workoutText.value.trim()) return
  
  isParsing.value = true
  
  try {
    const parsedExercises = await aiStore.parseWorkoutText(workoutText.value)
    
    // Transform parsed exercises to match our format
    exercises.value = parsedExercises.map((exercise: any) => ({
      type: exercise.type as WorkoutType,
      details: {
        distanceKm: exercise.details?.distanceKm,
        durationMin: exercise.details?.durationMin || 30,
        sets: exercise.details?.sets,
        repsPerSet: exercise.details?.repsPerSet,
        seconds: exercise.details?.seconds,
        notes: exercise.details?.notes || ''
      },
      kcalEstimated: exercise.kcalEstimated
    }))
    
    // Switch to form mode to show parsed exercises
    mode.value = 'form'
    
    // Show success message
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'success',
        message: t.workoutParsedSuccess
      })
    }
  } catch (error) {
    console.error('Error parsing workout text:', error)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'error',
        message: t.workoutParsedFailed
      })
    }
  } finally {
    isParsing.value = false
  }
}

async function handleSubmit() {
  if (!isFormValid.value) return

  isSubmitting.value = true

  try {
    let workoutData: any

    if (mode.value === 'text') {
      // In text mode, we need to parse the text first
      if (!workoutText.value.trim()) {
        throw new Error('Workout text is required')
      }
      
      const parsedExercises = await aiStore.parseWorkoutText(workoutText.value)
      
      // Transform parsed exercises to match our format
      const exercises = parsedExercises.map((exercise: any) => ({
        type: exercise.type as WorkoutType,
        details: {
          distanceKm: exercise.details?.distanceKm || undefined,
          durationMin: exercise.details?.durationMin || 30,
          sets: exercise.details?.sets || undefined,
          repsPerSet: exercise.details?.repsPerSet || undefined,
          seconds: exercise.details?.seconds || undefined,
          notes: exercise.details?.notes || ''
        },
        kcalEstimated: exercise.kcalEstimated || undefined
      }))
      
      workoutData = {
        date: new Date(formData.value.date),
        exercises,
        rpe: formData.value.rpe,
        notes: formData.value.notes
      }
    } else {
      // In form mode, use existing exercises
      workoutData = {
        date: new Date(formData.value.date),
        exercises: exercises.value.map(exercise => ({
          type: exercise.type,
          details: {
            distanceKm: exercise.details.distanceKm || undefined,
            durationMin: exercise.details.durationMin || 30,
            sets: exercise.details.sets || undefined,
            repsPerSet: exercise.details.repsPerSet || undefined,
            seconds: exercise.details.seconds || undefined,
            notes: exercise.details.notes || ''
          },
          kcalEstimated: exercise.kcalEstimated || undefined
        })),
        rpe: formData.value.rpe,
        notes: formData.value.notes
      }
    }

    let savedWorkout: Workout
    if (props.editMode && props.workout) {
      savedWorkout = await workoutsStore.updateWorkout(props.workout.id, workoutData)
    } else {
      savedWorkout = await workoutsStore.addWorkout(workoutData)
    }

    emit('saved', savedWorkout)
  } catch (error) {
    console.error('Error saving workout:', error)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'error',
        message: t.workoutSaveFailed
      })
    }
  } finally {
    isSubmitting.value = false
  }
}
</script>

// src/components/WorkoutForm.tsx
import React, { useState, useEffect } from 'react'
import { useWorkoutStore } from '../stores/workout.store'
import { useProfileStore } from '../stores/profile.store'
import { useTranslations, useI18nStore } from '../stores/i18n.store'
import { useAIStore } from '../stores/ai.store'
import { aiService } from '../services/ai'
import { calculateWorkoutCalories, calculateWorkoutDuration } from '../services/kcal'
import type { WorkoutExercise } from '../types/models'
import { X, Plus, Edit3, Bot } from 'lucide-react'
import ExerciseCard from './ExerciseCard'

interface WorkoutFormProps {
  isOpen: boolean
  onClose: () => void
  onSuccess?: () => void
}

const WorkoutForm: React.FC<WorkoutFormProps> = ({ isOpen, onClose, onSuccess }) => {
  const t = useTranslations()
  const { currentLanguage } = useI18nStore()
  const { addWorkout } = useWorkoutStore()
  const { profile } = useProfileStore()
  const { isConfigured: isAIConfigured } = useAIStore()
  
  const [mode, setMode] = useState<'form' | 'text'>('form')
  const [date, setDate] = useState(new Date().toISOString().split('T')[0])
  const [rpe, setRpe] = useState(5)
  const [exercises, setExercises] = useState<WorkoutExercise[]>([])
  const [textInput, setTextInput] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)

  // Reset form when opening
  useEffect(() => {
    if (isOpen) {
      setDate(new Date().toISOString().split('T')[0])
      setRpe(5)
      setExercises([])
      setTextInput('')
      setMode('form')
    }
  }, [isOpen])

  const addExercise = () => {
    const newExercise: WorkoutExercise = {
      type: 'run',
      details: {},
      kcalEstimated: 0
    }
    setExercises([newExercise, ...exercises])
  }

  const updateExercise = (index: number, updates: Partial<WorkoutExercise>) => {
    const updatedExercises = [...exercises]
    updatedExercises[index] = { ...updatedExercises[index], ...updates }
    
          // Recalculate calories if we have user weight
      if (profile?.weight) {
        updatedExercises[index].kcalEstimated = calculateExerciseCalories(
          updatedExercises[index],
          profile.weight
        )
      }
    
    setExercises(updatedExercises)
  }

  const removeExercise = (index: number) => {
    setExercises(exercises.filter((_, i) => i !== index))
  }

  const cloneExercise = (index: number) => {
    const cloned = { ...exercises[index] }
    setExercises([cloned, ...exercises])
  }

  const handleSave = async () => {
    if (exercises.length === 0) {
      alert('Please add at least one exercise')
      return
    }

    try {
      const workoutData = {
        date: new Date(date).toISOString(),
        exercises,
        rpe: rpe > 0 ? rpe : undefined,
        status: 'completed' as const
      }

      await addWorkout(workoutData)
      onSuccess?.()
      onClose()
    } catch (error) {
      console.error('Failed to save workout:', error)
      alert('Failed to save workout')
    }
  }

  const handleTextParse = async () => {
    if (!textInput.trim()) {
      alert(t.workoutForm?.pleaseEnterDescription || 'Please enter workout description')
      return
    }

    if (!isAIConfigured) {
      alert(t.workoutForm?.aiNotConfigured || 'AI is not configured. Please set up your OpenAI API key in Settings.')
      return
    }

    setIsProcessing(true)
    try {
      // Use AI to parse workout text
      const parsedExercises = await aiService.parseWorkoutText(textInput, currentLanguage)
      console.log(parsedExercises, '<<<parsedExercises')
      setExercises(parsedExercises as WorkoutExercise[])
      setMode('form')
    } catch (error) {
      console.error('Failed to parse workout text:', error)
      const errorMessage = error instanceof Error ? error.message : 'Unknown error'
      alert(t.workoutForm?.aiParseFailed || `AI parsing failed: ${errorMessage}`)
    } finally {
      setIsProcessing(false)
    }
  }


  const getRpeColor = (rpeValue: number) => {
    if (rpeValue <= 3) return 'text-green-600'
    if (rpeValue <= 7) return 'text-yellow-600'
    return 'text-red-600'
  }

  const getRpeLabel = (rpeValue: number) => {
    if (rpeValue <= 3) return t.workoutForm?.easy || 'Easy'
    if (rpeValue <= 7) return t.workoutForm?.moderate || 'Moderate'
    return t.workoutForm?.hard || 'Hard'
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900">
            {t.addWorkout}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Mode Toggle */}
        <div className="p-6 border-b border-gray-200">
          <div className="flex space-x-2">
            <button
              onClick={() => setMode('form')}
              className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors ${
                mode === 'form'
                  ? 'bg-primary-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              <Edit3 size={16} />
              <span>{t.workoutForm?.formMode || 'Form Mode'}</span>
            </button>
            <button
              onClick={() => setMode('text')}
              disabled={!isAIConfigured}
              className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors ${
                mode === 'text'
                  ? 'bg-primary-600 text-white'
                  : isAIConfigured 
                    ? 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                    : 'bg-gray-50 text-gray-400 cursor-not-allowed'
              }`}
            >
              <Bot size={16} />
              <span>{t.workoutForm?.textMode || 'Text Mode'}</span>
              {!isAIConfigured && (
                <span className="text-xs">(AI required)</span>
              )}
            </button>
          </div>
        </div>

        {mode === 'form' ? (
          /* Form Mode */
          <div className="p-6 space-y-6">
            {/* Basic Info */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  {t.workoutForm?.date || 'Date'}
                </label>
                <input
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  {t.workoutForm?.rpe || 'RPE (Rate of Perceived Exertion)'}
                </label>
                <div className="space-y-2">
                  <input
                    type="range"
                    min="1"
                    max="10"
                    value={rpe}
                    onChange={(e) => setRpe(parseInt(e.target.value))}
                    className="w-full"
                  />
                  <div className="flex justify-between text-sm">
                    <span className="text-green-600">1-3 {t.workoutForm?.easy || 'Easy'}</span>
                    <span className={`font-medium ${getRpeColor(rpe)}`}>
                      {rpe} - {getRpeLabel(rpe)}
                    </span>
                    <span className="text-red-600">8-10 {t.workoutForm?.hard || 'Hard'}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Exercises */}
            <div>
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-medium text-gray-900">{t.workoutForm?.exercises || 'Exercises'}</h3>
                <button
                  onClick={addExercise}
                  className="btn-primary flex items-center space-x-2"
                >
                  <Plus size={16} />
                  <span>{t.workoutForm?.addExercise || 'Add Exercise'}</span>
                </button>
              </div>

              <div className="space-y-4">
                {exercises.map((exercise, index) => (
                  <ExerciseCard
                    key={index}
                    exercise={exercise}
                    index={index}
                    onUpdate={(updates: Partial<WorkoutExercise>) => updateExercise(index, updates)}
                    onRemove={() => removeExercise(index)}
                    onClone={() => cloneExercise(index)}
                  />
                ))}
              </div>

              {exercises.length === 0 && (
                <div className="text-center py-8 text-gray-500">
                  <p>{t.workoutForm?.noExercisesAdded || 'No exercises added yet. Click "Add Exercise" to get started.'}</p>
                </div>
              )}
            </div>

            {/* Summary */}
            {exercises.length > 0 && profile?.weight && (
              <div className="bg-gray-50 rounded-lg p-4">
                <h4 className="font-medium text-gray-900 mb-2">{t.workoutForm?.workoutSummary || 'Workout Summary'}</h4>
                <div className="grid grid-cols-3 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600">{t.workoutForm?.totalCalories || 'Total Calories:'}</span>
                    <div className="font-medium">
                      {calculateWorkoutCalories(exercises, profile.weight, rpe)} kcal
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600">{t.workoutForm?.duration || 'Duration:'}</span>
                    <div className="font-medium">
                      {Math.round(calculateWorkoutDuration(exercises))} min
                    </div>
                  </div>
                  <div>
                    <span className="text-gray-600">{t.workoutForm?.exercisesCount || 'Exercises:'}</span>
                    <div className="font-medium">{exercises.length}</div>
                  </div>
                </div>
              </div>
            )}
          </div>
        ) : (
          /* Text Mode */
          <div className="p-6 space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                {t.workoutForm?.describeWorkout || 'Describe your workout'}
              </label>
              <textarea
                value={textInput}
                onChange={(e) => setTextInput(e.target.value)}
                rows={6}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                placeholder={t.workoutForm?.workoutDescriptionPlaceholder || "Example: пробежал 5 км, подтянулся 7-5-3-3-2, отжимания 20-20-15, планка 60-45-50"}
              />
              <p className="text-sm text-gray-500 mt-2">
                {t.workoutForm?.workoutDescriptionHelp || "Describe your workout in natural language. The AI will parse it into structured exercises."}
              </p>
            </div>

            <button
              onClick={handleTextParse}
              disabled={isProcessing || !textInput.trim()}
              className="btn-primary w-full disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isProcessing ? (t.workoutForm?.parsing || 'Parsing...') : (t.workoutForm?.parseAndContinue || 'Parse and Continue')}
            </button>
          </div>
        )}

        {/* Footer */}
        <div className="flex justify-end space-x-4 p-6 border-t border-gray-200">
          <button
            onClick={onClose}
            className="btn-secondary"
          >
            {t.cancel}
          </button>
          {mode === 'form' && (
            <button
              onClick={handleSave}
              disabled={exercises.length === 0}
              className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {t.save}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// Helper function for calculating exercise calories
function calculateExerciseCalories(
  exercise: WorkoutExercise,
  userWeight: number
): number {
  // This is a simplified version - the full implementation is in kcal.ts
  const baseMET = 4.0 // Default MET value
  let duration = 0

  switch (exercise.type) {
    case 'run':
      duration = exercise.details.durationMin || 0
      break
    case 'pullups':
    case 'pushups':
      if (exercise.details.repsPerSet) {
        const totalReps = exercise.details.repsPerSet.reduce((sum, reps) => sum + reps, 0)
        duration = totalReps * 2 / 60 // 2 seconds per rep
      }
      break
    case 'plank':
      if (exercise.details.seconds) {
        const totalSeconds = exercise.details.seconds.reduce((sum, seconds) => sum + seconds, 0)
        duration = totalSeconds / 60
      }
      break
    case 'custom':
      duration = exercise.details.durationMin || 0
      break
  }

  return Math.round((baseMET * userWeight * duration * 3.5) / 200)
}

export default WorkoutForm
