// src/features/workout/WorkoutDetailsPage.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <header class="bg-white shadow-sm border-b border-gray-200">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-4">
          <div class="flex items-center">
            <router-link 
              to="/workouts" 
              class="p-2 text-gray-400 hover:text-gray-600 transition-colors mr-2"
            >
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
              </svg>
            </router-link>
            <h1 class="text-2xl font-bold text-gray-900">Workout Details</h1>
          </div>
          <div class="flex space-x-2">
            <button
              @click="showEditForm = true"
              class="btn-secondary"
            >
              Edit
            </button>
            <button
              @click="deleteWorkout"
              class="bg-red-600 hover:bg-red-700 text-white font-medium py-2 px-4 rounded-lg transition-colors duration-200"
            >
              Delete
            </button>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Loading State -->
      <div v-if="isLoading" class="text-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
        <p class="mt-4 text-gray-600">Loading workout details...</p>
      </div>

      <!-- Workout Details -->
      <div v-else-if="workout" class="space-y-6">
        <!-- Workout Info Card -->
        <div class="card">
          <div class="flex items-center justify-between mb-6">
            <div class="flex items-center">
              <div class="w-12 h-12 bg-primary-100 rounded-full flex items-center justify-center">
                <span class="text-lg font-medium text-primary-600">
                  {{ getWorkoutTypeIcon(workout.type) }}
                </span>
              </div>
              <div class="ml-4">
                <h2 class="text-2xl font-bold text-gray-900">
                  {{ formatWorkoutType(workout.type) }}
                </h2>
                <p class="text-gray-600">{{ formatDate(workout.date) }}</p>
              </div>
            </div>
            <div class="text-right">
              <div class="text-3xl font-bold text-primary-600">
                {{ workout.calories }} kcal
              </div>
              <div class="text-sm text-gray-500">Burned</div>
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-4">Workout Details</h3>
              <div class="space-y-3">
                <div class="flex justify-between">
                  <span class="text-gray-600">Duration:</span>
                  <span class="font-medium">{{ workout.durationMin }} minutes</span>
                </div>
                <div v-if="workout.distance" class="flex justify-between">
                  <span class="text-gray-600">Distance:</span>
                  <span class="font-medium">{{ workout.distance }} km</span>
                </div>
                <div v-if="workout.reps" class="flex justify-between">
                  <span class="text-gray-600">Reps:</span>
                  <span class="font-medium">{{ workout.reps }}</span>
                </div>
                <div v-if="workout.sets" class="flex justify-between">
                  <span class="text-gray-600">Sets:</span>
                  <span class="font-medium">{{ workout.sets }}</span>
                </div>
                <div v-if="workout.weight" class="flex justify-between">
                  <span class="text-gray-600">Weight:</span>
                  <span class="font-medium">{{ workout.weight }} kg</span>
                </div>
                <div v-if="workout.customExercise" class="flex justify-between">
                  <span class="text-gray-600">Exercise:</span>
                  <span class="font-medium">{{ workout.customExercise }}</span>
                </div>
              </div>
            </div>

            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-4">Notes</h3>
              <div v-if="workout.notes" class="bg-gray-50 rounded-lg p-4">
                <p class="text-gray-700">{{ workout.notes }}</p>
              </div>
              <div v-else class="text-gray-500 italic">
                No notes added
              </div>
            </div>
          </div>
        </div>

        <!-- AI Analysis -->
        <div v-if="aiPlan" class="card">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">AI Analysis</h3>
          <PlanCard :plan="aiPlan" />
        </div>

        <!-- AI Analysis Button -->
        <div v-else class="card">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">AI Analysis</h3>
          <p class="text-gray-600 mb-4">
            Get AI-powered analysis and recommendations for your next workout.
          </p>
          <button
            @click="evaluateWorkout"
            :disabled="isEvaluating"
            class="btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="isEvaluating">Analyzing...</span>
            <span v-else>Analyze with AI</span>
          </button>
        </div>
      </div>

      <!-- Not Found -->
      <div v-else class="text-center py-12">
        <div class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <svg class="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.172 16.172a4 4 0 015.656 0M9 12h6m-6-4h6m2 5.291A7.962 7.962 0 0112 15c-2.34 0-4.47-.881-6.08-2.33"></path>
          </svg>
        </div>
        <h3 class="text-lg font-medium text-gray-900 mb-2">Workout not found</h3>
        <p class="text-gray-600 mb-6">The workout you're looking for doesn't exist or has been deleted.</p>
        <router-link 
          to="/workouts" 
          class="btn-primary"
        >
          Back to Workouts
        </router-link>
      </div>

      <!-- Edit Form Modal -->
      <div v-if="showEditForm && workout" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
        <div class="relative top-10 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
          <div class="mt-3">
            <h3 class="text-lg font-medium text-gray-900 mb-4">Edit Workout</h3>
            <WorkoutForm 
              :workout="workout"
              :edit-mode="true"
              @saved="handleWorkoutUpdated"
              @cancel="showEditForm = false"
            />
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useWorkoutsStore } from '@/stores/workouts.store'
import { useAIStore } from '@/stores/ai.store'
import { format } from 'date-fns'
import WorkoutForm from '@/components/WorkoutForm.vue'
import PlanCard from '@/components/PlanCard.vue'
import type { Workout } from '@/types/models'

const route = useRoute()
const router = useRouter()
const workoutsStore = useWorkoutsStore()
const aiStore = useAIStore()

const isLoading = ref(false)
const isEvaluating = ref(false)
const showEditForm = ref(false)

// Computed
const workout = computed(() => workoutsStore.workouts.find(w => w.id === route.params.id))
const aiPlan = computed(() => aiStore.aiPlans.find(p => p.workoutId === route.params.id))

// Methods
function formatWorkoutType(type: string): string {
  const types: Record<string, string> = {
    run: 'Running',
    pullups: 'Pull-ups',
    pushups: 'Push-ups',
    plank: 'Plank',
    custom: 'Custom Exercise'
  }
  return types[type] || type
}

function getWorkoutTypeIcon(type: string): string {
  const icons: Record<string, string> = {
    run: '🏃',
    pullups: '💪',
    pushups: '🏋️',
    plank: '🧘',
    custom: '⚡'
  }
  return icons[type] || '⚡'
}

function formatDate(date: Date): string {
  return format(new Date(date), 'EEEE, MMM d, yyyy')
}

async function evaluateWorkout() {
  if (!workout.value) return
  
  isEvaluating.value = true
  
  try {
    await aiStore.reviewWorkout(workout.value.id)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'success',
        message: 'Workout analyzed! Check the AI analysis below.'
      })
    }
  } catch (error) {
    console.error('Error evaluating workout:', error)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'error',
        message: 'Failed to analyze workout. Please check your AI settings.'
      })
    }
  } finally {
    isEvaluating.value = false
  }
}

async function deleteWorkout() {
  if (!workout.value) return
  
  if (!confirm('Are you sure you want to delete this workout? This action cannot be undone.')) {
    return
  }
  
  try {
    await workoutsStore.deleteWorkout(workout.value.id)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'success',
        message: 'Workout deleted successfully!'
      })
    }
    
    router.push('/workouts')
  } catch (error) {
    console.error('Error deleting workout:', error)
    
    if ((window as any).showToast) {
      ;(window as any).showToast({
        type: 'error',
        message: 'Failed to delete workout. Please try again.'
      })
    }
  }
}

function handleWorkoutUpdated(updatedWorkout: Workout) {
  showEditForm.value = false
  
  if ((window as any).showToast) {
    ;(window as any).showToast({
      type: 'success',
      message: 'Workout updated successfully!'
    })
  }
}

// Lifecycle
onMounted(async () => {
  isLoading.value = true
  
  try {
    await Promise.all([
      workoutsStore.loadWorkouts(),
      aiStore.loadAIPlans()
    ])
  } finally {
    isLoading.value = false
  }
})
</script>

// src/features/workout/WorkoutDetailsPage.tsx
import React, { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'

import { useWorkoutStore } from '../../stores/workout.store'
import { useProfileStore } from '../../stores/profile.store'
import { useTranslations } from '../../stores/i18n.store'
import { calculateWorkoutCalories, calculateWorkoutDuration } from '../../services/kcal'
import { format } from 'date-fns'
import { ArrowLeft, Edit, Trash2, TrendingUp, Check, X } from 'lucide-react'
import type { WorkoutExercise } from '../../types/models'

const WorkoutDetailsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const t = useTranslations()

  const { getWorkoutById, deleteWorkout, updateWorkout } = useWorkoutStore()
  const { profile } = useProfileStore()
  
  const [workout, setWorkout] = useState(getWorkoutById(id!))
  const [isDeleting, setIsDeleting] = useState(false)
  
  // Inline editing states
  const [editingHeader, setEditingHeader] = useState(false)
  const [editingExercise, setEditingExercise] = useState<number | null>(null)
  const [editedDate, setEditedDate] = useState('')
  const [editedRpe, setEditedRpe] = useState(5)
  const [editedExercise, setEditedExercise] = useState<WorkoutExercise | null>(null)
  const [isSaving, setIsSaving] = useState(false)
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null)

  useEffect(() => {
    if (!workout && id) {
      setWorkout(getWorkoutById(id))
    }
  }, [id, workout, getWorkoutById])

  if (!workout) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">{t.workoutDetailsPage?.workoutNotFound || 'Workout not found'}</h2>
          <button
            onClick={() => navigate('/workouts')}
            className="btn-primary"
          >
            {t.workoutDetailsPage?.backToWorkouts || 'Back to Workouts'}
          </button>
        </div>
      </div>
    )
  }

  const totalCalories = profile?.weight 
    ? calculateWorkoutCalories(workout.exercises, profile.weight, workout.rpe)
    : 0
  const totalDuration = calculateWorkoutDuration(workout.exercises)

  const getRpeColor = (rpe: number) => {
    if (rpe <= 3) return 'text-green-600 bg-green-100'
    if (rpe <= 7) return 'text-yellow-600 bg-yellow-100'
    return 'text-red-600 bg-red-100'
  }

  const getRpeLabel = (rpe: number) => {
    if (rpe <= 3) return t.workoutForm?.easy || 'Easy'
    if (rpe <= 7) return t.workoutForm?.moderate || 'Moderate'
    return t.workoutForm?.hard || 'Hard'
  }

  const getExerciseTypeName = (type: string) => {
    return t.exerciseTypes?.[type as keyof typeof t.exerciseTypes] || type
  }

  const handleDelete = async () => {
    if (confirm(t.workoutDetailsPage?.deleteConfirm || 'Are you sure you want to delete this workout?')) {
      setIsDeleting(true)
      try {
        await deleteWorkout(workout.id)
        navigate('/workouts')
      } catch (error) {
        console.error('Failed to delete workout:', error)
        alert(t.workoutDetailsPage?.failedToDelete || 'Failed to delete workout')
      } finally {
        setIsDeleting(false)
      }
    }
  }

  // Inline editing functions
  const startEditingHeader = () => {
    setEditedDate(workout!.date.split('T')[0])
    setEditedRpe(workout!.rpe || 5)
    setEditingHeader(true)
  }

  const startEditingExercise = (index: number) => {
    setEditedExercise({ ...workout!.exercises[index] })
    setEditingExercise(index)
  }

  const cancelEditing = () => {
    setEditingHeader(false)
    setEditingExercise(null)
    setEditedExercise(null)
  }

  const saveHeader = async () => {
    if (!workout) return
    
    setIsSaving(true)
    try {
      const updatedWorkout = {
        ...workout,
        date: new Date(editedDate).toISOString(),
        rpe: editedRpe
      }
      
      await updateWorkout(workout.id, updatedWorkout)
      setWorkout(updatedWorkout)
      setEditingHeader(false)
      showToast(t.workoutDetailsPage?.workoutUpdated || 'Workout updated successfully', 'success')
    } catch (error) {
      console.error('Failed to update workout:', error)
      showToast(t.workoutDetailsPage?.updateFailed || 'Failed to update workout', 'error')
    } finally {
      setIsSaving(false)
    }
  }

  const saveExercise = async () => {
    if (!workout || editingExercise === null || !editedExercise) return
    
    setIsSaving(true)
    try {
      const updatedExercises = [...workout.exercises]
      updatedExercises[editingExercise] = editedExercise
      
      const updatedWorkout = {
        ...workout,
        exercises: updatedExercises
      }
      
      await updateWorkout(workout.id, updatedWorkout)
      setWorkout(updatedWorkout)
      setEditingExercise(null)
      setEditedExercise(null)
      showToast(t.workoutDetailsPage?.exerciseUpdated || 'Exercise updated successfully', 'success')
    } catch (error) {
      console.error('Failed to update exercise:', error)
      showToast(t.workoutDetailsPage?.updateFailed || 'Failed to update exercise', 'error')
    } finally {
      setIsSaving(false)
    }
  }

  const showToast = (message: string, type: 'success' | 'error') => {
    setToast({ message, type })
    setTimeout(() => setToast(null), 3000)
  }

  const renderExerciseEditFields = () => {
    if (!editedExercise) return null

    const updateExerciseField = (field: string, value: any) => {
      setEditedExercise(prev => prev ? {
        ...prev,
        details: { ...prev.details, [field]: value }
      } : null)
    }

    const updateExerciseType = (type: string) => {
      setEditedExercise(prev => prev ? { ...prev, type: type as any } : null)
    }

    return (
      <div className="space-y-4">
        {/* Exercise Type */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t.workoutDetailsPage?.exerciseType || 'Exercise Type'}
          </label>
          <select
            value={editedExercise.type}
            onChange={(e) => updateExerciseType(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
          >
            <option value="run">{t.exerciseTypes?.run || 'Run'}</option>
            <option value="pullups">{t.exerciseTypes?.pullups || 'Pull-ups'}</option>
            <option value="pushups">{t.exerciseTypes?.pushups || 'Push-ups'}</option>
            <option value="plank">{t.exerciseTypes?.plank || 'Plank'}</option>
            <option value="custom">{t.exerciseTypes?.custom || 'Custom'}</option>
          </select>
        </div>

        {/* Type-specific fields */}
        {editedExercise.type === 'run' && (
          <>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {t.workoutDetailsPage?.distance || 'Distance'} ({t.workoutCard?.km || 'km'})
                </label>
                <input
                  type="number"
                  step="0.1"
                  value={editedExercise.details.distanceKm || ''}
                  onChange={(e) => updateExerciseField('distanceKm', parseFloat(e.target.value) || 0)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {t.workoutDetailsPage?.duration || 'Duration'} ({t.workoutDetailsPage?.minutes || 'minutes'})
                </label>
                <input
                  type="number"
                  value={editedExercise.details.durationMin || ''}
                  onChange={(e) => updateExerciseField('durationMin', parseInt(e.target.value) || 0)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                />
              </div>
            </div>
          </>
        )}

        {(editedExercise.type === 'pullups' || editedExercise.type === 'pushups') && (
          <>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {t.workoutDetailsPage?.sets || 'Sets'}
              </label>
              <input
                type="number"
                value={editedExercise.details.sets || ''}
                onChange={(e) => updateExerciseField('sets', parseInt(e.target.value) || 0)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {t.workoutDetailsPage?.repsPerSet || 'Reps per set'} ({t.workoutDetailsPage?.commaSeparated || 'comma separated'})
              </label>
              <input
                type="text"
                value={editedExercise.details.repsPerSet?.join(',') || ''}
                onChange={(e) => updateExerciseField('repsPerSet', e.target.value.split(',').map(r => parseInt(r.trim())).filter(r => !isNaN(r)))}
                placeholder="10,8,6"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              />
            </div>
          </>
        )}

        {editedExercise.type === 'plank' && (
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t.workoutDetailsPage?.seconds || 'Seconds'} ({t.workoutDetailsPage?.commaSeparated || 'comma separated'})
            </label>
            <input
              type="text"
              value={editedExercise.details.seconds?.join(',') || ''}
              onChange={(e) => updateExerciseField('seconds', e.target.value.split(',').map(s => parseInt(s.trim())).filter(s => !isNaN(s)))}
              placeholder="60,45,30"
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
            />
          </div>
        )}

        {editedExercise.type === 'custom' && (
          <>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {t.workoutDetailsPage?.exerciseName || 'Exercise Name'}
              </label>
              <input
                type="text"
                value={editedExercise.details.customExercise || ''}
                onChange={(e) => updateExerciseField('customExercise', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {t.workoutDetailsPage?.duration || 'Duration'} ({t.workoutDetailsPage?.minutes || 'minutes'})
                </label>
                <input
                  type="number"
                  value={editedExercise.details.durationMin || ''}
                  onChange={(e) => updateExerciseField('durationMin', parseInt(e.target.value) || 0)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  {t.workoutDetailsPage?.repsPerSet || 'Reps per set'} ({t.workoutDetailsPage?.commaSeparated || 'comma separated'})
                </label>
                <input
                  type="text"
                  value={editedExercise.details.repsPerSet?.join(',') || ''}
                  onChange={(e) => updateExerciseField('repsPerSet', e.target.value.split(',').map(r => parseInt(r.trim())).filter(r => !isNaN(r)))}
                  placeholder="20,15,10"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                />
              </div>
            </div>
          </>
        )}

        {/* Notes field for all types */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            {t.workoutDetailsPage?.notes || 'Notes'}
          </label>
          <textarea
            value={editedExercise.details.notes || ''}
            onChange={(e) => updateExerciseField('notes', e.target.value)}
            rows={2}
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
          />
        </div>

        {/* Action buttons */}
        <div className="flex space-x-2">
          <button
            onClick={saveExercise}
            disabled={isSaving}
            className="btn-primary flex items-center space-x-1"
          >
            <Check size={16} />
            <span>{isSaving ? (t.saving || 'Saving...') : (t.save || 'Save')}</span>
          </button>
          <button
            onClick={cancelEditing}
            disabled={isSaving}
            className="btn-secondary flex items-center space-x-1"
          >
            <X size={16} />
            <span>{t.cancel || 'Cancel'}</span>
          </button>
        </div>
      </div>
    )
  }

  const formatExerciseDetails = (exercise: any) => {
    switch (exercise.type) {
      case 'run':
        return `${exercise.details.distanceKm || 0} ${t.workoutCard?.km || 'km'} ${t.workoutDetailsPage?.for || 'in'} ${exercise.details.durationMin || 0} ${t.workoutDetailsPage?.minutes || 'minutes'}`
      case 'pullups':
      case 'pushups':
        if (exercise.details.repsPerSet) {
          const totalReps = exercise.details.repsPerSet.reduce((sum: number, reps: number) => sum + reps, 0)
          return `${exercise.details.sets || 0} ${t.workoutDetailsPage?.sets || 'sets'}: ${exercise.details.repsPerSet.join('-')} (${totalReps} ${t.workoutDetailsPage?.total || 'total'})`
        }
        return t.workoutDetailsPage?.noRepsSpecified || 'No reps specified'
      case 'plank':
        if (exercise.details.seconds) {
          const totalSeconds = exercise.details.seconds.reduce((sum: number, seconds: number) => sum + seconds, 0)
          return `${exercise.details.seconds.length} ${t.workoutDetailsPage?.holds || 'holds'}: ${exercise.details.seconds.join('-')}s (${totalSeconds}s ${t.workoutDetailsPage?.total || 'total'})`
        }
        return t.workoutDetailsPage?.noTimeSpecified || 'No time specified'
      case 'custom':
        if (exercise.details.customExercise) {
          if (exercise.details.durationMin) {
            return `${exercise.details.customExercise} ${t.workoutDetailsPage?.for || 'for'} ${exercise.details.durationMin} ${t.workoutDetailsPage?.minutes || 'minutes'}`
          } else if (exercise.details.repsPerSet) {
            const totalReps = exercise.details.repsPerSet.reduce((sum: number, reps: number) => sum + reps, 0)
            return `${exercise.details.customExercise}: ${exercise.details.sets || 0} ${t.workoutDetailsPage?.sets || 'sets'}: ${exercise.details.repsPerSet.join('-')} (${totalReps} ${t.workoutDetailsPage?.total || 'total'})`
          }
        }
        return t.workoutDetailsPage?.customExercise || 'Custom exercise'
      default:
        return t.workoutDetailsPage?.exerciseDetails || 'Exercise details'
    }
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <div className="flex items-center space-x-4">
            <button
              onClick={() => navigate('/workouts')}
              className="btn-secondary flex items-center space-x-2"
            >
              <ArrowLeft size={20} />
              <span>{t.workoutDetailsPage?.backToWorkouts || 'Back to Workouts'}</span>
            </button>
            <h1 className="text-3xl font-bold text-gray-900">{t.workoutDetailsPage?.workoutDetails || 'Workout Details'}</h1>
          </div>
          
          <div className="flex items-center space-x-3">
            <button
              onClick={handleDelete}
              disabled={isDeleting}
              className="btn-secondary text-red-600 hover:text-red-700 flex items-center space-x-2"
            >
              <Trash2 size={16} />
              <span>{isDeleting ? (t.workoutDetailsPage?.deleting || 'Deleting...') : (t.workoutDetailsPage?.delete || 'Delete')}</span>
            </button>
          </div>
        </div>

        {/* Workout Summary */}
        <div className={`card mb-8 ${editingHeader ? 'ring-2 ring-primary-500 bg-primary-50' : ''}`}>
          <div className="flex justify-between items-start mb-6">
            <div className="flex-1">
              {editingHeader ? (
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {t.workoutForm?.date || 'Date'}
                    </label>
                    <input
                      type="date"
                      value={editedDate}
                      onChange={(e) => setEditedDate(e.target.value)}
                      className="px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      {t.workoutForm?.rpe || 'RPE'}
                    </label>
                    <div className="space-y-2">
                      <input
                        type="range"
                        min="1"
                        max="10"
                        value={editedRpe}
                        onChange={(e) => setEditedRpe(parseInt(e.target.value))}
                        className="w-full max-w-xs"
                      />
                      <div className="flex justify-between text-sm max-w-xs">
                        <span className="text-green-600">1-3 {t.workoutForm?.easy || 'Easy'}</span>
                        <span className={`font-medium ${getRpeColor(editedRpe)}`}>
                          {editedRpe} - {getRpeLabel(editedRpe)}
                        </span>
                        <span className="text-red-600">8-10 {t.workoutForm?.hard || 'Hard'}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex space-x-2">
                    <button
                      onClick={saveHeader}
                      disabled={isSaving}
                      className="btn-primary flex items-center space-x-1"
                    >
                      <Check size={16} />
                      <span>{isSaving ? (t.saving || 'Saving...') : (t.save || 'Save')}</span>
                    </button>
                    <button
                      onClick={cancelEditing}
                      disabled={isSaving}
                      className="btn-secondary flex items-center space-x-1"
                    >
                      <X size={16} />
                      <span>{t.cancel || 'Cancel'}</span>
                    </button>
                  </div>
                </div>
              ) : (
                <>
                  <h2 className="text-2xl font-bold text-gray-900 mb-2">
                    {format(new Date(workout.date), 'EEEE, MMMM d, yyyy')}
                  </h2>
                  {workout.rpe && (
                    <span className={`inline-block px-3 py-1 rounded-full text-sm font-medium ${getRpeColor(workout.rpe)}`}>
                      RPE {workout.rpe} - {getRpeLabel(workout.rpe)}
                    </span>
                  )}
                </>
              )}
            </div>
            
            <div className="flex items-center space-x-2">
              {!editingHeader && (
                <button
                  onClick={startEditingHeader}
                  className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
                  title={t.workoutDetailsPage?.editWorkout || 'Edit workout'}
                >
                  <Edit size={16} />
                </button>
              )}
              
              {workout.aiReviewId && (
                <div className="flex items-center space-x-2 text-primary-600">
                  <TrendingUp size={20} />
                  <span className="font-medium">{t.workoutDetailsPage?.aiReviewed || 'AI Reviewed'}</span>
                </div>
              )}
            </div>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="text-3xl font-bold text-blue-600 mb-2">{totalCalories}</div>
              <div className="text-sm text-gray-600">{t.workoutDetailsPage?.totalCalories || 'Total Calories'}</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-green-600 mb-2">{Math.round(totalDuration)}</div>
              <div className="text-sm text-gray-600">{t.workoutDetailsPage?.duration || 'Duration (minutes)'}</div>
            </div>
        <div className="text-center">
              <div className="text-3xl font-bold text-purple-600 mb-2">{workout.exercises.length}</div>
              <div className="text-sm text-gray-600">{t.workoutDetailsPage?.exercises || 'Exercises'}</div>
            </div>
          </div>
        </div>

        {/* Exercises */}
        <div className="card">
          <h3 className="text-lg font-semibold text-gray-900 mb-6">{t.workoutDetailsPage?.exercises || 'Exercises'}</h3>
          
          <div className="space-y-4">
            {workout.exercises.map((exercise, index) => (
              <div key={index} className={`border border-gray-200 rounded-lg p-4 ${editingExercise === index ? 'ring-2 ring-primary-500 bg-primary-50' : ''}`}>
                {editingExercise === index ? (
                  renderExerciseEditFields()
                ) : (
                  <>
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <h4 className="font-semibold text-gray-900 capitalize">
                          {exercise.type === 'custom' && exercise.details.customExercise
                            ? exercise.details.customExercise
                            : getExerciseTypeName(exercise.type)
                          }
                        </h4>
                        <p className="text-sm text-gray-600">
                          {formatExerciseDetails(exercise)}
                        </p>
                      </div>
                      
                      <div className="flex items-center space-x-2">
                        <button
                          onClick={() => startEditingExercise(index)}
                          className="p-1 text-gray-400 hover:text-gray-600 transition-colors"
                          title={t.workoutDetailsPage?.editExercise || 'Edit exercise'}
                        >
                          <Edit size={16} />
                        </button>
                        
                        {exercise.kcalEstimated && exercise.kcalEstimated > 0 && (
                          <div className="text-sm text-gray-500">
                            ~{exercise.kcalEstimated} kcal
                          </div>
                        )}
                      </div>
                    </div>
                    
                    {exercise.details.notes && (
                      <div className="mt-3 p-3 bg-gray-50 rounded-lg">
                        <p className="text-sm text-gray-700">{exercise.details.notes}</p>
                      </div>
                    )}
                  </>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* AI Analysis (if available) */}
        {workout.aiReviewId && (
          <div className="card mt-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4 flex items-center space-x-2">
              <TrendingUp size={20} className="text-primary-600" />
              <span>{t.workoutDetailsPage?.aiAnalysis || 'AI Analysis'}</span>
            </h3>
            <p className="text-gray-600">
              {t.workoutDetailsPage?.aiAnalysisDescription || 'This workout has been analyzed by AI. View the full analysis and recommendations in the AI section.'}
            </p>
          </div>
        )}

        {/* Toast Notification */}
        {toast && (
          <div className={`fixed top-4 right-4 z-50 p-4 rounded-lg shadow-lg ${
            toast.type === 'success' 
              ? 'bg-green-100 border border-green-200 text-green-800' 
              : 'bg-red-100 border border-red-200 text-red-800'
          }`}>
            <div className="flex items-center space-x-2">
              {toast.type === 'success' ? (
                <Check size={16} className="text-green-600" />
              ) : (
                <X size={16} className="text-red-600" />
              )}
              <span className="text-sm font-medium">{toast.message}</span>
        </div>
      </div>
        )}
      </main>
    </div>
  )
}

export default WorkoutDetailsPage
